apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - image: ricoms858/divorce-predictor:latest
        imagePullPolicy: Always
        name: capstone-app
        command: ["serve"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /health-check/liveness
            port: 8080
            httpHeaders:
             - name: Custom-Header
               value: Awesome
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 90
          periodSeconds: 20
          failureThreshold: 30
