Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
Resources:
  CapstoneEKS:
    Type: AWS::EKS::Cluster
    Properties:
      Name: CapstoneEKS
      Version: '1.16'
      RoleArn: arn:aws:iam::695404701427:role/eks-role
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-SCG"
        SubnetIds:
            Fn::Split:
                - ","
                - Fn::ImportValue:
                      Fn::Sub: ${EnvironmentName}-SBN-IDS
Outputs:
  EksId:
    Description: The EKS id.
    Value: !Ref CapstoneEKS
    Export:
        Name: !Sub ${EnvironmentName}-EKS


